docs: write explanatory comments on the query_* function in the sample contract
Finschia/cosmwasm pull request #318
Opened 2023-07-14 09:49 UTC by 170210

# Description
This PR has following changes.

- change the proof.proto path to third_party/proto/confio

Closes #317 

## Types of changes

- [ ] Bug fix (changes which fixes an issue)
- [ ] New feature (changes which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] ETC (build, ci, docs, perf, refactor, style, test)

## Checklist

- [ ] I followed the [contributing guidelines](https://github.com/Finschia/cosmwasm/blob/main/CONTRIBUTING.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] The PR title and commits are followed [conventional commit form](https://www.conventionalcommits.org/en/v1.0.0).

2023-07-14 09:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Finschia/cosmwasm?pullRequest=318) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Finschia/cosmwasm?pullRequest=318) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Finschia/cosmwasm?pullRequest=318) it.</sub>

2023-07-18 01:51 UTC, loloicci submitted a review, later dismissed

2023-07-18 01:52 UTC, loloicci commented
> change the proof.proto path to third_party/proto/confio

Please fix the description of this PR. (maybe mistake)

2023-07-20 01:52 UTC, kokeshiM0chi submitted a review, later dismissed
Change the title prefix. Sorry for the late review. Is `comment:` better?

2023-07-20 02:06 UTC, zemyblue commented
Please use `chore: ` structural elements.

2023-07-20 02:30 UTC, da1suk8 reviewed
It's a bit detailed, but I feel that "panic" makes it seem as if a panic is occurring, so it would be helpful if you could correct it to say that an error is occurring.

2023-07-21 07:14 UTC, da1suk8 approved these changes

2023-07-21 07:19 UTC, loloicci approved these changes

2023-07-21 07:21 UTC, loloicci requested changes

2023-07-21 07:21 UTC, loloicci commented on contracts/call-number/src/contract.rs
> +// when a caller with read-only permissions attempts to call a callable point with read/write permissions.
```suggestion
// This function is used to check if an appropriate error has been occurred in the VM
// when a caller with read-only permissions attempts to call a callable point with read/write permissions.
```

2023-07-21 07:21 UTC, loloicci commented on contracts/call-number/src/contract.rs
> +// when a caller with read-only permissions attempts to call a callable point with read/write permissions.
```suggestion
// This function is used to check if an appropriate error has been occurred in the VM
// when a caller with read-only permissions attempts to call a callable point with read/write permissions.
```

2023-07-21 07:21 UTC, loloicci commented on contracts/call-number/src/contract.rs
> +// when a caller with read-only permissions attempts to call a callable point with read/write permissions.
```suggestion
// This function is used to check if an appropriate error has been occurred in the VM
// when a caller with read-only permissions attempts to call a callable point with read/write permissions.
```

2023-07-21 07:33 UTC, da1suk8 approved these changes

2023-07-21 08:01 UTC, loloicci approved these changes

2023-07-21 08:01 UTC, merged